<h1>コンストラクタ (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">nested_exception() noexcept;
nested_exception(const nested_exception&amp;) noexcept = default;</span></code></pre>
</p>
<h2>nested_exceptionオブジェクトの構築</h2>
<ul>
<li><code><span style="color: #000">nested_exception() noexcept;</span></code><br /><a href="http://cpprefjp.github.io/reference/exception/current_exception.html"><code><span style="color: #000">current_exception()</span></code></a>を呼び出し、その戻り値をメンバ変数として保持する。</li>
</ul>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;exception&gt;
#include &lt;iostream&gt;

class my_exception : public std::nested_exception {};

int main()
{
  try {
    try {
      throw 1;
    }
    catch (int&amp; x) {
      my_exception e; // 現在の例外(int)が保持される

      // my_exceptionによって入れ子になった例外へのポインタを取得して再送出
      std::rethrow_exception(e.nested_ptr());
    }
  }
  catch (int&amp; x) {
    std::cout &lt;&lt; x &lt;&lt; std::endl;
  }
} </span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">1
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: 3</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.7.0</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> ??</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/nested_exception/nested_exception.md" target="_blank">編集</a></footer>