<h1>stdexcept</h1>
<p><code><span style="color: #000">&lt;stdexcept&gt;</span></code>ヘッダは、標準的な例外クラスを提供する。<br />
これらの例外クラスは、標準ライブラリ内でも使用されている。</p>
<p>これらのクラス群に反映されているエラーモデルでは、エラーは「実行時エラー (runtime error) 」と「論理エラー (logic error) 」との２つに大別される。<br />
論理エラーを区別するための性質は、それがプログラムの内部的論理の誤りに起因することである。理論的には、それらは予め避けることができる。<br />
対して、実行時エラーはプログラムの制御の及ばない事象に起因する。それらを前もって簡単に予見することはできない。</p>
<p>このヘッダで提供される例外クラスは以下の表の通りである。以下のクラスは全て、<code><span style="color: #000">std</span></code>名前空間で提供される。</p>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><code><span style="color: #000">logic_error</span></code></td>
<td>プログラムの実行前に検出可能なエラー（論理エラー）を示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">domain_error</span></code></td>
<td>定義域エラーを示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">invalid_argument</span></code></td>
<td>不正な引数を示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">length_error</span></code></td>
<td>長すぎるオブジェクトを作ろうとしたことを示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">out_of_range</span></code></td>
<td>引数が許容範囲外であることを示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">runtime_error</span></code></td>
<td>プログラム実行時にのみ検出可能なエラー（実行時エラー）を示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">range_error</span></code></td>
<td>内部計算によって、値が範囲外になったことを示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">overflow_error</span></code></td>
<td>数値計算の結果がオーバーフローしたことを示す</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">underflow_error</span></code></td>
<td>数値計算の結果がアンダーフローしたことを示す</td>
<td></td>
</tr>
</tbody>
</table>
<p>例外クラスには継承関係があり、以下の箇条書きの階層構造で示す。</p>
<ul>
<li><a href="http://cpprefjp.github.io/reference/exception/exception.html"><code><span style="color: #000">exception</span></code></a><ul>
<li><code><span style="color: #000">logic_error</span></code><ul>
<li><code><span style="color: #000">domain_error</span></code></li>
<li><code><span style="color: #000">invalid_argument</span></code></li>
<li><code><span style="color: #000">length_error</span></code></li>
<li><code><span style="color: #000">out_of_range</span></code></li>
</ul>
</li>
<li><code><span style="color: #000">runtime_error</span></code><ul>
<li><code><span style="color: #000">range_error</span></code></li>
<li><code><span style="color: #000">overflow_error</span></code></li>
<li><code><span style="color: #000">underflow_error</span></code></li>
</ul>
</li>
</ul>
</li>
</ul>
<p><a href="http://cpprefjp.github.io/reference/exception/exception.html"><code><span style="color: #000">exception</span></code></a>クラスを除く9つのクラスは、すべて同じ<code><span style="color: #000">public</span></code>メンバ関数をもつ。 </p>
<p>クラス名を<code><span style="color: #000">T</span></code>とすると、以下の<code><span style="color: #000">public</span></code>メンバ関数をもつ。</p>
<h2>メンバ関数</h2>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><code><span style="color: #000">explicit T(const</span></code> <a href="http://cpprefjp.github.io/reference/string/basic_string.html"><code><span style="color: #000">string</span></code></a><code><span style="color: #000">&amp; what_arg);</span></code></td>
<td>指定したメッセージを持つ例外オブジェクトを生成する</td>
<td></td>
</tr>
<tr>
<td><code><span style="color: #000">explicit T(const char* what_arg);</span></code></td>
<td>指定したメッセージを持つ例外オブジェクトを生成する</td>
<td>C++11</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual const char* what() const noexcept;</span></code></td>
<td>メッセージを取得する</td>
<td></td>
</tr>
</tbody>
</table>
<h2>例</h2>
<p>ここでは、簡単な例外処理の例を示す。</p>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;stdexcept&gt;
#include &lt;iostream&gt;
#include &lt;cstdlib&gt; // exit

void f()
{
  // 例外を投げる
  throw std::logic_error("an exception occurred");
}

int main()
{
  try {
    f();
  }
  catch (const std::logic_error&amp; e) {
    // 例外が発生した！
    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;
    exit(1);
  }
}</span></code></pre>
</p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/stdexcept.md" target="_blank">編集</a></footer>