<h1>generic_category (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><a href="http://cpprefjp.github.io/reference/system_error/error_category.html">error_category</a>&amp; generic_category() noexcept;
}<span style="color: #000">namespace std {
  const </span></code></pre>
</p>
<h2>概要</h2>
<p>汎用エラーに関する<code><span style="color: #000">error_category</span></code>を返す。
ここでの「汎用」とは、<code><span style="color: #000">&lt;cerrno&gt;</span></code>ヘッダで定義される環境依存しないエラー値、およびそれに対応する<a href="http://cpprefjp.github.io/reference/system_error/errc.html"><code><span style="color: #000">std::errc</span></code></a>列挙値によるエラー情報を指す。</p>
<h2>戻り値</h2>
<p><a href="http://cpprefjp.github.io/reference/system_error/error_category.html"><code><span style="color: #000">error_category</span></code></a>クラスを継承したクラスオブジェクトへの参照を返す。 
この関数を呼び出すことによって返されるオブジェクトは、同じオブジェクトを指す。 
この関数によって返されるオブジェクトのクラスは以下の特徴を持つ：</p>
<ul>
<li><a href="http://cpprefjp.github.io/reference/system_error/error_category/name.html"><code><span style="color: #000">name()</span></code></a>関数によって返される文字列は<code><span style="color: #000">"generic"</span></code></li>
<li><a href="http://cpprefjp.github.io/reference/system_error/error_category/default_error_condition.html"><code><span style="color: #000">default_error_condition()</span></code></a>仮想関数および<a href="http://cpprefjp.github.io/reference/system_error/error_category/equivalent.html"><code><span style="color: #000">equivalent()</span></code></a>仮想関数の挙動は、基本クラスである<a href="http://cpprefjp.github.io/reference/system_error/error_category.html"><code><span style="color: #000">error_category</span></code></a>と同じである</li>
</ul>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">generic_category</span>();

  std::cout &lt;&lt; cat.name() &lt;&lt; std::endl;
  std::cout &lt;&lt; cat.message(static_cast&lt;int&gt;(std::errc::invalid_argument)) &lt;&lt; std::endl;
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;system_error&gt;
#include &lt;string&gt;

int main()
{
  const std::error_category&amp; cat = std::</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">generic
Invalid argument
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.6.1</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> 10.0</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/system_error/generic_category.md" target="_blank">編集</a></footer>