<h1>future_error (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><a href="http://cpprefjp.github.io/reference/stdexcept.html">logic_error</a>;
}<span style="color: #000">namespace std {
  class future_error : public </span></code></pre>
</p>
<h2>概要</h2>
<p><code><span style="color: #000">future_error</span></code>は、<a href="http://cpprefjp.github.io/reference/future/future.html"><code><span style="color: #000">future</span></code></a>/<a href="http://cpprefjp.github.io/reference/future/promise.html"><code><span style="color: #000">promise</span></code></a>操作でのエラーを扱うための例外クラスである。</p>
<h3>メンバ関数</h3>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><code><span style="color: #000">future_error(</span></code><a href="http://cpprefjp.github.io/reference/system_error/error_code.html"><code><span style="color: #000">error_code</span></code></a><code><span style="color: #000">ec);</span></code></td>
<td><a href="http://cpprefjp.github.io/reference/system_error/error_code.html"><code><span style="color: #000">error_code</span></code></a>オブジェクトから<code><span style="color: #000">future_error</span></code>オブジェクトを生成する。<br />注：このクラスは標準ライブラリの内部で送出される例外クラスで、ユーザーが使用するものではないため、コンストラクタは説明のためにのみ記載されている。</td>
</tr>
<tr>
<td><code><span style="color: #000">const</span></code><a href="http://cpprefjp.github.io/reference/system_error/error_code.html"><code><span style="color: #000">error_code</span></code></a><code><span style="color: #000">&amp; code() const noexcept;</span></code></td>
<td>包含している<a href="http://cpprefjp.github.io/reference/system_error/error_code.html"><code><span style="color: #000">error_code</span></code></a>オブジェクトへの参照を取得する</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual const char* what() const noexcept;</span></code></td>
<td>エラー理由となる実装依存文字列(<code><span style="color: #000">code.</span></code><a href="http://cpprefjp.github.io/reference/system_error/error_code/message.html"><code><span style="color: #000">message</span></code></a><code><span style="color: #000">()</span></code>)を返す</td>
</tr>
</tbody>
</table>
<h3>例</h3>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;iostream&gt;
#include &lt;future&gt;
#include &lt;thread&gt;
#include &lt;utility&gt;

void foo(std::promise&lt;int&gt; p)
{
  p.set_value(3);

  try {
    p.set_value(1); // promiseに2回以上書き込むとエラー
  }
  catch (std::future_error&amp; e) {
    std::cout &lt;&lt; "value:" &lt;&lt; e.code().value() &lt;&lt; std::endl;
    std::cout &lt;&lt; "what:" &lt;&lt; e.what() &lt;&lt; std::endl;
  }
}

int main()
{
  std::promise&lt;int&gt; p;
  std::future&lt;int&gt; f = p.get_future();

  std::thread t(foo, std::move(p));

  std::cout &lt;&lt; f.get() &lt;&lt; std::endl;

  t.join();
}</span></code></pre>
</p>
<h3>出力例</h3>
<p><pre><code><span style="color: #000">3
value:3
what:Promise already satisfied
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.7.0</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a>: 11.0</li>
</ul>
<h3>参照</h3>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/future/future_error.md" target="_blank">編集</a></footer>